import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { SiteChrome } from "@/components/layout/SiteChrome";
import { ConsentBanner } from "@/components/consent/ConsentBanner";
import { SITE_URL } from "@/lib/constants";
import { getFeatureFlags } from "@/lib/api/railway";
import { ogImage } from "@/lib/og";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false,
});

const SITE_TAGLINE = "AudioForges: Free Tools for Producers, DJs and Musicians";
const SITE_DESCRIPTION =
  "Free browser audio tools for producers, DJs and musicians. Every model is named, every limit is published, and results play back before you download.";

/**
 * The site-wide fallback card, generated by /api/og like every other page's.
 * This is what shows for any route that doesn't set its own openGraph.images.
 */
const OG_IMAGE = ogImage("AudioForges", "Free audio tools for producers, DJs and musicians.");

export const viewport: Viewport = {
  themeColor: "#151515",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TAGLINE,
    template: "%s | AudioForges",
  },
  description: SITE_DESCRIPTION,
  openGraph: {
    title: SITE_TAGLINE,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: "AudioForges",
    images: [OG_IMAGE],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TAGLINE,
    description: SITE_DESCRIPTION,
    images: [OG_IMAGE.url],
  },
  other: {
    "ahrefs-site-verification":
      "c1354acdd4f3553f046ae70968ed850f6cd1ce5052618ccdd4a8b660096cd308",
  },
};

/**
 * `logo` is the brand mark (public/images/logo.png), NOT an OG card. Google's
 * Organization logo expects the logo on its own — square-ish, at least
 * 112×112 — so pointing it at a 1200×630 social banner, as this used to, meant
 * the image Google associated with AudioForges was a headline graphic.
 *
 * logo.svg is the source; logo.png is rasterized from it so the two can't
 * drift. logo-mono.svg is the currentColor version for press and for dark
 * backgrounds where the orange won't hold.
 */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "AudioForges",
  url: SITE_URL,
  logo: `${SITE_URL}/images/logo.png`,
  sameAs: [
    "https://www.youtube.com/@dipakshah4672",
    "https://www.instagram.com/audioforges/",
    "https://www.producthunt.com/products/audioforges",
    "https://github.com/dipak8080/audioforges_nextjs",
    "https://ko-fi.com/audioforges",
    "https://www.saashub.com/audioforges",
  ],
};

// EEA + UK + Switzerland. gtag resolves the region by IP on its own, so
// visitors outside it keep full analytics without ever seeing a banner.
const CONSENT_REGIONS = [
  "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR",
  "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK",
  "SI", "ES", "SE", "IS", "LI", "NO", "GB", "CH",
];

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // Resolved HERE, once, server-side — so CreditProvider makes ZERO client
  // requests on the ~90 pages of this site while the paywall is off.
  //
  // This does NOT make the site dynamic: getFeatureFlags() uses
  // `next: { revalidate: 86400 }`, so pages stay static with ISR. It also
  // fails closed and has a 5s deadline, so a dead VPS renders the site
  // normally with the paywall reading as off rather than hanging the
  // render.
  const { paywallEnabled, paywallTools } = await getFeatureFlags();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        {/* Consent defaults MUST execute before gtag.js, which is why this is
            beforeInteractive. Denied in the EEA/UK/CH until the visitor
            chooses; granted everywhere else. */}
        <Script id="consent-mode-default" strategy="beforeInteractive">
          {`
    window.dataLayer = window.dataLayer || [];
    window.gtag = window.gtag || function(){window.dataLayer.push(arguments);};
    gtag('consent', 'default', {
      ad_storage: 'denied',
      ad_user_data: 'denied',
      ad_personalization: 'denied',
      analytics_storage: 'denied',
      region: ${JSON.stringify(CONSENT_REGIONS)},
      wait_for_update: 2000
    });
    gtag('consent', 'default', {
      ad_storage: 'granted',
      ad_user_data: 'granted',
      ad_personalization: 'granted',
      analytics_storage: 'granted'
    });
  `}
        </Script>

        {/* Google tag (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-4MW6XTR9XM"
          strategy="lazyOnload"
        />

        <Script id="google-analytics" strategy="lazyOnload">
          {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-4MW6XTR9XM');
  `}
        </Script>

        {/* Ahrefs Analytics has no consent-mode integration, so it is injected
            by ConsentBanner only once analytics storage is allowed. */}

        {/* Site-wide Organization schema — only needs to appear once, not
            per-page, since it describes the publisher/brand rather than any
            individual page's content. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />

        <SiteChrome flags={{ paywallEnabled, paywallTools }}>{children}</SiteChrome>
        <ConsentBanner />
      </body>
    </html>
  );
}