import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { SiteChrome } from "@/components/layout/SiteChrome";
import { SITE_URL } from "@/lib/constants";
import { getFeatureFlags } from "@/lib/api/railway";
import { ogImage } from "@/lib/og";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_TAGLINE = "AudioForges — Free Audio Tools for Producers";
const SITE_DESCRIPTION =
  "Free audio tools for music producers and DJs — YouTube to WAV/MP3 conversion, key & BPM detection, and more.";

/**
 * The site-wide fallback card, generated by /api/og like every other page's.
 * This is what shows for any route that doesn't set its own openGraph.images.
 */
const OG_IMAGE = ogImage("AudioForges", "Free audio tools for producers, DJs and musicians.");

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TAGLINE,
    template: "%s | AudioForges",
  },
  description: SITE_DESCRIPTION,
  openGraph: {
    title: SITE_TAGLINE,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: "AudioForges",
    images: [OG_IMAGE],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TAGLINE,
    description: SITE_DESCRIPTION,
    images: [OG_IMAGE.url],
  },
  other: {
    "ahrefs-site-verification":
      "c1354acdd4f3553f046ae70968ed850f6cd1ce5052618ccdd4a8b660096cd308",
  },
};

/**
 * `logo` is the brand mark (public/images/logo.png), NOT an OG card. Google's
 * Organization logo expects the logo on its own — square-ish, at least
 * 112×112 — so pointing it at a 1200×630 social banner, as this used to, meant
 * the image Google associated with AudioForges was a headline graphic.
 *
 * The asset is the same Lucide AudioWaveform mark the navbar uses, amber on
 * graphite. logo.svg sits beside it if it ever needs regenerating at another
 * size.
 */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "AudioForges",
  url: SITE_URL,
  logo: `${SITE_URL}/images/logo.png`,
  sameAs: [
    "https://www.producthunt.com/products/audioforges",
    "https://github.com/dipak8080/audioforges_nextjs",
    "https://ko-fi.com/audioforges",
    "https://alternativeto.net/software/audioforges/",
  ],
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // Resolved HERE, once, server-side — so CreditProvider makes ZERO client
  // requests on the ~90 pages of this site while the paywall is off.
  //
  // This does NOT make the site dynamic: getFeatureFlags() uses
  // `next: { revalidate: 60 }`, so pages stay static with ISR. It also
  // fails closed and has a 5s deadline, so a dead VPS renders the site
  // normally with the paywall reading as off rather than hanging the
  // render.
  const { paywallEnabled, paywallTools } = await getFeatureFlags();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        {/* Google tag (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-4MW6XTR9XM"
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-4MW6XTR9XM');
  `}
        </Script>

        {/* Ahrefs Analytics */}
        <Script
          src="https://analytics.ahrefs.com/analytics.js"
          data-key="QkVPNT1O6u+JbZ5njmaMTw"
          strategy="afterInteractive"
        />

        {/* Site-wide Organization schema — only needs to appear once, not
            per-page, since it describes the publisher/brand rather than any
            individual page's content. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />

        <SiteChrome flags={{ paywallEnabled, paywallTools }}>{children}</SiteChrome>
      </body>
    </html>
  );
}